language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sublime-project' ]; then cd .. && eval "mv $currentfolder generator-sublime-project" && cd generator-sublime-project; fi

